### ISSUE TITLE
Add the ability to define policies for a cluster

### ISSUE THREAD

**Issue by pranaypareek** [kube-flux/kube-flux#9]
TODO: make a checkbox list that mentions each story associated with this particular epic

- [x] Define data model for `policy` object #10

- [x] Create a CRUD (create, read, update, delete) APIs for `policy` objects #11

- [ ] Generate swagger docs for the project, specifically document the `policy` API #12

- [ ] Write tests for each API end point related to the `policy` object #13
